### ISSUE TITLE
Issue in the key, value sorted items

### ISSUE THREAD

**Issue by korymath** [kylemath/DeepEEG#3]
```
>>> from utils import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/korymathewson/work/DeepEEG/utils.py", line 212
    for key, value in sorted(event_id.iteritems(), key=lambda (k,v): (v,k)):
                                                              ^
SyntaxError: invalid syntax
```

Minor issue in how these are being called, should use a method that is compatible.

**Comment by korymath** [comment]
I think that this is the fix:

```
for key, value in sorted(event_id.items(), key=lambda item: (item[1], item[0])):
```

**Comment by kylemath** [comment]
Why did you reopen? 
what does the lambda do?

**Comment by kylemath** [comment]
how do recreate this error?

**Comment by korymath** [comment]
Reopened because I closed by accident. 

I started python, and then imported:
```
from utils import *
``` 

And it threw the error. Lambda is a small, anonymous function... for instance:

```
x = lambda a : a + 10
print(x(5))
```

**Comment by korymath** [comment]
This is fixed for python3 with https://github.com/kylemath/DeepEEG/pull/5
